# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29800da70bb59188920be449fff463952b10948c9c1af68da36fe568268b7ad4566abc7c879bf54eeb2ad991037c4cb3df150c4337e3eec31f9b491bf0575565

test:
  secret_key_base: cfaebf2df2935892662458e29a40d669628d7f779d5b47ce070e6f79ae6848b2c126c00a98144e0902f8d94276634df3b962d772271a275b878ad9e065d7b963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
